### ISSUE TITLE
Custom Exception

### ISSUE THREAD

**Issue by AdamGold** [davekch/pycurry#1]
I thought it would be nice to have a custom exception so developers won't be confused by the ``TypeError`` getting thrown to other ``TypeError`` exceptions. What do you think?

**Comment by davekch** [comment]
nice idea. Maybe pass a custom exception to `curry`? something like

    class MyException(Exception):
        pass

    @curry(int,int, exception=MyException)
    def f(x,y):
        return x+y

This way you would not be forced to use a custom exception.

**Comment by AdamGold** [comment]
Nice. Do you want me to make a PR?

**Comment by davekch** [comment]
sure, thanks!

**Comment by davekch** [comment]
fixed in #2
